/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bases;

/**
 *
 * @author Equipo 4
 */
public class Ayuda extends javax.swing.JFrame {

    /**
     * Creates new form Ayuda
     */
    public Ayuda() {                 //constructor
        initComponents();            // componentes de interfaz
        this.setLocationRelativeTo(null);
        setTitle("Manual de usuario"); //Titulo de ventana
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ayuda = new javax.swing.JPanel();
        Manual = new javax.swing.JLabel();
        informacion = new javax.swing.JLabel();
        decoracion = new javax.swing.JPanel();
        logoUpiicsa = new javax.swing.JLabel();
        Barra = new javax.swing.JMenuBar();
        Inicio = new javax.swing.JMenu();
        regresaInicio = new javax.swing.JMenuItem();
        salir = new javax.swing.JMenuItem();
        Ayuda1 = new javax.swing.JMenu();
        volver = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Ayuda.setBackground(new java.awt.Color(0, 153, 51));

        Manual.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        Manual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Manual.setText("Ayuda ");

        informacion.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        informacion.setText("<html> BIENVENID@ AL CONVERTIDOR DE BASES NUMÉRICAS <p> <p> El convertidor de bases numéricas es una aplicación que te ayuda a calcular el valor de un número desde una base origen a una base destino <p> <p> ¿Cómo usar el CONVERTIDOR DE BASES NUMÉRICAS?  <p> 1.- Elija la base origen del número que desea convertir (De base 2 a 16) <p> 2.- Ingresa el numero que deseas convertir (solo admite 10 carácteres) <p> 3.- Elija la base destino en que se convertira el número ingresado (De base 2 a 16) <p> 4.- Presione \"Convertir\" <p>  5.- Obten tu resultado <p> 6.- Para hacer una nueva conversión presiona \"Limpiar\" </html>");

        decoracion.setBackground(new java.awt.Color(255, 255, 0));

        logoUpiicsa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Escudo_UPIICSA (1).png"))); // NOI18N
        logoUpiicsa.setText("jLabel1");

        javax.swing.GroupLayout decoracionLayout = new javax.swing.GroupLayout(decoracion);
        decoracion.setLayout(decoracionLayout);
        decoracionLayout.setHorizontalGroup(
            decoracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, decoracionLayout.createSequentialGroup()
                .addContainerGap(549, Short.MAX_VALUE)
                .addComponent(logoUpiicsa, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        decoracionLayout.setVerticalGroup(
            decoracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoUpiicsa, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout AyudaLayout = new javax.swing.GroupLayout(Ayuda);
        Ayuda.setLayout(AyudaLayout);
        AyudaLayout.setHorizontalGroup(
            AyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(decoracion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AyudaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(informacion, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(AyudaLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(Manual, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AyudaLayout.setVerticalGroup(
            AyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AyudaLayout.createSequentialGroup()
                .addComponent(decoracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(Manual, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(informacion, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        Inicio.setText("Inicio");

        regresaInicio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        regresaInicio.setText("Regresar a Inicio");
        regresaInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresaInicioActionPerformed(evt);
            }
        });
        Inicio.add(regresaInicio);

        salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        Inicio.add(salir);

        Barra.add(Inicio);

        Ayuda1.setText("Conversor");

        volver.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        volver.setText("Volver... ");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        Ayuda1.add(volver);

        Barra.add(Ayuda1);

        setJMenuBar(Barra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Ayuda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Ayuda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresaInicioActionPerformed
        Inicio a= new Inicio(); //Boton "regresar" de menuBar manda a ventana "Inicio"
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_regresaInicioActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        Conversor a= new Conversor(); //Boton "volver" de menuBar manda a ventana "Conversor"
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_volverActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        dispose();   //Boton "Salir" de menuBar sale de la aplicacion 
    }//GEN-LAST:event_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ayuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ayuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ayuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ayuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ayuda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Ayuda;
    private javax.swing.JMenu Ayuda1;
    private javax.swing.JMenuBar Barra;
    private javax.swing.JMenu Inicio;
    private javax.swing.JLabel Manual;
    private javax.swing.JPanel decoracion;
    private javax.swing.JLabel informacion;
    private javax.swing.JLabel logoUpiicsa;
    private javax.swing.JMenuItem regresaInicio;
    private javax.swing.JMenuItem salir;
    private javax.swing.JMenuItem volver;
    // End of variables declaration//GEN-END:variables
}
